CREATE TABLE locations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address varchar(255),
    district varchar(100),
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    place_id varchar(255)
);

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    email varchar(150) NOT NULL UNIQUE,
    name varchar(100) NOT NULL,
    password varchar(255) NOT NULL,
    role varchar(255) NOT NULL CHECK (role IN ('USER', 'ADMIN')),
    location_id bigint UNIQUE REFERENCES locations(id)
);

CREATE TABLE plans (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget double precision,
    closed_at timestamp(6),
    created_at timestamp(6) NOT NULL,
    description varchar(1000),
    feasibility_score integer NOT NULL,
    feasibility_status varchar(255) NOT NULL
        CHECK (feasibility_status IN ('NOT_VIABLE', 'TO_BE_DEFINED', 'READY_TO_CLOSE')),
    invite_code varchar(12) NOT NULL UNIQUE,
    min_participants integer NOT NULL,
    name varchar(100) NOT NULL,
    status varchar(255) NOT NULL CHECK (status IN ('OPEN', 'CLOSED', 'CANCELLED')),
    tentative_end_date date,
    tentative_start_date date,
    type varchar(255) NOT NULL
        CHECK (type IN ('DINNER', 'PARTY', 'TRIP', 'SPORTS', 'CULTURAL', 'STUDY', 'OTHER')),
    version bigint NOT NULL,
    creator_id bigint NOT NULL REFERENCES users(id)
);

CREATE TABLE plan_participants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invited_at timestamp(6) NOT NULL,
    joined_at timestamp(6),
    role varchar(255) NOT NULL CHECK (role IN ('ORGANIZER', 'GUEST')),
    status varchar(255) NOT NULL CHECK (status IN ('INVITED', 'JOINED')),
    plan_id bigint NOT NULL REFERENCES plans(id),
    user_id bigint NOT NULL REFERENCES users(id),
    CONSTRAINT uq_plan_participant UNIQUE (plan_id, user_id)
);

CREATE TABLE plan_options (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    avg_distance_km double precision,
    avg_travel_minutes integer,
    description varchar(500),
    ends_at timestamp(6),
    label varchar(120) NOT NULL,
    selected boolean NOT NULL,
    starts_at timestamp(6),
    type varchar(255) NOT NULL CHECK (type IN ('DATE', 'PLACE')),
    version bigint NOT NULL,
    location_id bigint UNIQUE REFERENCES locations(id),
    plan_id bigint NOT NULL REFERENCES plans(id),
    proposed_by_id bigint NOT NULL REFERENCES users(id)
);

CREATE TABLE votes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    option_id bigint NOT NULL REFERENCES plan_options(id),
    user_id bigint NOT NULL REFERENCES users(id),
    CONSTRAINT uq_vote_option_user UNIQUE (option_id, user_id)
);

CREATE TABLE availabilities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    available_date date NOT NULL,
    end_time time(0),
    start_time time(0),
    plan_id bigint NOT NULL REFERENCES plans(id),
    user_id bigint NOT NULL REFERENCES users(id)
);

CREATE TABLE commitment_responses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note varchar(255),
    responded_at timestamp(6) NOT NULL,
    status varchar(255) NOT NULL CHECK (status IN ('CONFIRMED', 'INTERESTED', 'CANT_GO')),
    plan_id bigint NOT NULL REFERENCES plans(id),
    user_id bigint NOT NULL REFERENCES users(id),
    CONSTRAINT uq_commitment_plan_user UNIQUE (plan_id, user_id)
);

CREATE TABLE notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    message varchar(500) NOT NULL,
    read_at timestamp(6),
    sent_at timestamp(6),
    status varchar(255) NOT NULL CHECK (status IN ('PENDING', 'SENT', 'FAILED')),
    type varchar(255) NOT NULL CHECK (type IN
        ('PLAN_INVITATION', 'PLAN_UPDATED', 'MIN_PARTICIPANTS_REACHED', 'PLAN_CLOSED', 'PLAN_CANCELLED')),
    plan_id bigint REFERENCES plans(id),
    recipient_id bigint NOT NULL REFERENCES users(id)
);

CREATE INDEX idx_availabilities_plan_date ON availabilities (plan_id, available_date);
CREATE INDEX idx_notifications_recipient ON notifications (recipient_id);
CREATE INDEX idx_plan_options_plan ON plan_options (plan_id);
CREATE INDEX idx_plan_participants_user ON plan_participants (user_id);
CREATE INDEX idx_plans_creator ON plans (creator_id);
CREATE INDEX idx_plans_status ON plans (status);
